import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Icons } from '@/components/Icons';
import { SearchBar } from '@/components/SearchBar';
import Link from 'next/link';
import Others from '@/components/Others';
import { ThemeProvider } from '@/components/ThemeProvider';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="relative min-h-screen isolate overflow-hidden border-b border-gray-500 ">
            <svg
              className="absolute inset-0 -z-10 h-full w-full stroke-gray-200 [mask-image:radial-gradient(100%_100%_at_top_right,white,transparent)]"
              aria-hidden="true"
            >
              <defs>
                <pattern
                  id="0787a7c5-978c-4f66-83c7-11c213f99cb7"
                  width={200}
                  height={200}
                  x="50%"
                  y={-1}
                  patternUnits="userSpaceOnUse"
                >
                  <path d="M.5 200V.5H200" fill="none" />
                </pattern>
              </defs>
              <rect
                width="100%"
                height="100%"
                strokeWidth={0}
                fill="url(#0787a7c5-978c-4f66-83c7-11c213f99cb7)"
              />
            </svg>
            <div className="mx-auto max-w-7xl px-6 pb-24 pt-10 sm:pb-32 lg:flex gap-16 lg:px-8 lg:py-24 ">
              <div className="h-full w-full flex flex-col items-center gap-4">
                <Link href="/">
                  <Icons.Sparkles className="h-16 w-16" />
                </Link>

                <h1 className="tracking-tight text-4xl sm:text-6xl font-bold  ">
                  VectorSearch
                </h1>
                <p className="max-w-xl text-center text-lg ">
                  Hybrid search engine that enhances search accuracy by querying
                  semantically related results. Powered by Postgresql full text
                  search and{' '}
                  <Link
                    target="_blank"
                    className="hover:text-green-500 text-blue-500"
                    href={`https://huggingface.co/mixedbread-ai/mxbai-embed-large-v1`}
                  >
                    mixedbread-ai
                  </Link>{' '}
                  sentence transformer model. `Ctrl + k` to focus and try
                  searching for `Jacket` to see related results.
                </p>
                <Others />
                <div className="mx-auto mt-16 w-full max-w-2xl flex flex-col">
                  <SearchBar />
                  {children}
                </div>
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
